In [2]:
import numpy as np
import pandas as pd
dataset = pd.read_csv('iris.data', header=None)

In [3]:
def sw_sb_calculation(data,feature_number):
    class_means = data.groupby(4).mean()
    sw = np.zeros((feature_number, feature_number))
    for c, rows in data.groupby(4):
        rows = rows.drop([4], axis=1)
        s = np.zeros((feature_number, feature_number))
        for index, row in rows.iterrows():
            x = row.values.reshape(feature_number, 1)
            xm = class_means.loc[c].values.reshape(feature_number, 1)
            s += (x - xm).dot((x - xm).T)
        sw += s

    total_mean = data.mean()
    sb = np.zeros((feature_number, feature_number))
    for c in class_means.index:
        n = len(data.loc[data[4] == c].index)
        m_m = class_means.loc[c].values.reshape(feature_number, 1)
        m = total_mean.values.reshape(feature_number, 1)
        sb += n * (m_m - m).dot((m_m - m).T)

    return sw,sb

In [46]:
# setosa and versicolor

tot_1 = dataset[0:100].copy()
feature_number = tot_1.shape[1]-1
X = tot_1.iloc[0:100,0:4]
s_w,s_b = sw_sb_calculation(tot_1,feature_number)
eigen_values1, eigen_vectors1 = np.linalg.eig(np.linalg.inv(s_w).dot(s_b))
print(eigen_values1)


[0.00000000e+00 2.65079234e+01 2.12976067e-15 3.12420622e-15]


In [49]:
# from eigen_values list we can say the second one contains as much as data, so we can determind it as the w*
print("w* = ",eigen_vectors1[1])

w* =  [-0.15044621 -0.42695115  0.97271919 -0.92056431]


In [50]:
result1 = X.dot(eigen_vectors1[1])
# classified results, two classes
print(result)

0    -1.083911
1    -0.840346
2    -0.992919
3    -0.740635
4    -1.111561
        ...   
95    0.842347
96    0.792985
97    0.815034
98    0.070883
99    0.738408
Length: 100, dtype: float64


In [51]:
# check classification performance
total_num = result1.shape[0]
postive_num = 0
negative_num = 0
setosa_num = 0
versicolor_num = 0
for i in range(total_num):
    if(tot_1.iloc[i,4] == 'Iris-setosa'):
        setosa_num += 1
    else:
        versicolor_num += 1
    if(result1[i]< 0):
        negative_num += 1
    else:
        postive_num += 1 

In [52]:
print(setosa_num,versicolor_num,negative_num,postive_num)
# the Fishers LDA works perfect on the first pair of classes.

50 50 50 50


In [53]:
# Second pair :setosa and virginica

In [59]:
tot_2 = dataset[0:50].append(dataset[100:150]).copy()
tot_2 = tot_2.reset_index(drop=True)
feature_number = tot_2.shape[1]-1
X = tot_2.iloc[0:100,0:4]
s_w,s_b = sw_sb_calculation(tot_2,feature_number)
eigen_values2, eigen_vectors2 = np.linalg.eig(np.linalg.inv(s_w).dot(s_b))
print(eigen_values2)



[ 0.00000000e+00  4.99632944e+01 -3.39232469e-15  4.54585100e-15]


In [60]:
# we do the same thing, set w* qual to the second eigen_vector.
print(eigen_vectors2[1])

[-0.08246051 -0.22080764  0.31344308 -0.22387536]


In [56]:
result2 = X.dot(eigen_vectors2[1])
print(result2)


0    -0.799330
1    -0.672434
2    -0.731448
3    -0.638432
4    -0.813165
        ...   
95   -0.099918
96    0.070332
97   -0.016263
98   -0.084322
99    0.046644
Length: 100, dtype: float64


In [63]:
total_num = result2.shape[0]
postive_num = 0
negative_num = 0
setosa_num = 0
virginica_num = 0
for i in range(total_num):
    if(tot_2.iloc[i,4] == 'Iris-setosa'):
        setosa_num += 1
    else:
        virginica_num += 1
    if(result2[i]< 0):
        negative_num += 1
    else:
        postive_num += 1 

In [64]:
print(setosa_num,versicolor_num,negative_num,postive_num)
# rate = (postive_corrected_num+negative_corrected_num)/total_num
print((50+34)/100)
# the Fishers LDA works not that good on the second pair with 0.84 corrected rate.

50 50 66 34
0.84


In [61]:
# Thrid pair : versicolor and virginica
tot_3 = dataset[50:150].copy()
tot_3 = tot_3.reset_index(drop=True)
feature_number = tot_3.shape[1]-1
X = tot_3.iloc[0:100,0:4]
s_w,s_b = sw_sb_calculation(tot_3,feature_number)
eigen_values3, eigen_vectors3 = np.linalg.eig(np.linalg.inv(s_w).dot(s_b))
print(eigen_values3)



[-8.88178420e-16+0.00000000e+00j  3.62726679e+00+0.00000000e+00j
  7.35449502e-16+5.27671386e-16j  7.35449502e-16-5.27671386e-16j]


In [62]:
# we do the same thing, set w* qual to the second eigen_vector.
print(eigen_vectors3[1])

[-0.18843348+0.j -0.35584988+0.j  0.90863569+0.j  0.90863569-0.j]


In [75]:
result3 = X.dot(eigen_vectors3[1])
# classified results, two classes
print(result3)

0     3.084924+0.000000j
1     3.107120+0.000000j
2     3.411943+0.000000j
3     2.960930+0.000000j
4     3.321480+0.000000j
             ...        
95    4.484714+0.000000j
96    4.192831+0.000000j
97    4.249810+0.000000j
98    4.618318+0.000000j
99    4.090279+0.000000j
Length: 100, dtype: complex128


In [69]:
total_num = result3.shape[0]
postive_num = 0
negative_num = 0
versicolor_num = 0
virginica_num = 0
for i in range(total_num):
    if(tot_3.iloc[i,4] == 'Iris-versicolor'):
        versicolor_num += 1
    else:
        virginica_num += 1
    if(result3[i]< 0):
        negative_num += 1
    else:
        postive_num += 1 

In [76]:
print(versicolor_num,virginica_num,negative_num,postive_num)
# from the result, we can see the Fisher LDA can't work on versicolor and virginica

50 50 0 100


In [ ]:
# Conclusion:
# 1:There is huge linear difference between setosa and versicolor which we can perform LDA perfectly.
# 2:There is some linear difference between setosa and virginica which we can still perform LDA with near 84% correct rate.
# 3: There is no linear difference between versicolor and virginica Or i can say they are almost same Iris that we can't
# distinguish them by the four features